import { test } from 'node:test'; import * as assert from 'node:assert/strict';
import { AgentRuntime } from './agent-runtime'; import { LlmProvider, AgentTool } from './contracts'; import { ToolRegistry } from '../tools/tool-registry';
class FakeProvider implements LlmProvider { calls=0; observed:any[]=[]; toolChoices:any[]=[]; async complete(input:any){ this.observed.push(structuredClone(input.messages)); this.toolChoices.push(input.toolChoice); this.calls++; if(this.calls===1)return {message:{role:'assistant' as const,content:null,tool_calls:[{id:'t1',type:'function' as const,function:{name:'tool_a',arguments:'{}'}}]}}; if(this.calls===2)return {message:{role:'assistant' as const,content:null,tool_calls:[{id:'t2',type:'function' as const,function:{name:'tool_b',arguments:'{"roomId":"r1"}'}}]}}; return {message:{role:'assistant' as const,content:'verified final'},usage:{promptTokens:10,completionTokens:5}}; } }
function tool(name:string):AgentTool{return {readOnly:true,timeoutMs:1000,authorize:c=>c.role==='ADMIN',definition:{type:'function',function:{name,description:name,strict:true,parameters:{type:'object',additionalProperties:false,properties:{}}}},validate:x=>(x??{}) as any,execute:async(input)=>({ok:true,data:{name,input},meta:{generatedAt:new Date().toISOString(),freshnessStatus:'FRESH',durationMs:0,sources:['test']}})}}
test('native multi-step loop returns tool results to model before final synthesis',async()=>{const registry=new ToolRegistry();registry.register(tool('tool_a'));registry.register(tool('tool_b'));const provider=new FakeProvider();const events:any[]=[];const result=await new AgentRuntime(provider,registry,{record:async event=>{events.push(event)}}).run({goal:'investigate',systemPolicy:'policy',model:'fake',context:{runId:'run1',role:'ADMIN'},budget:{maxIterations:5,maxToolCalls:5,maxTokens:1000,timeoutMs:5000}});assert.equal(result.status,'COMPLETED');assert.equal(result.toolCalls,2);assert.equal(result.iterations,3);assert.equal(provider.observed[1].at(-1).role,'tool');assert.equal(provider.observed[2].at(-1).role,'tool');assert.equal(result.final,'verified final');assert.deepEqual(events.map(x=>[x.step,x.toolName,x.status]),[[1,'tool_a','RUNNING'],[1,'tool_a','COMPLETED'],[2,'tool_b','RUNNING'],[2,'tool_b','COMPLETED']]);assert.deepEqual(provider.toolChoices[0],{type:'function',function:{name:'get_room_economics'}});assert.deepEqual(provider.toolChoices.slice(1),['auto','auto']);});
test('tool budget stops the loop safely',async()=>{const registry=new ToolRegistry();registry.register(tool('tool_a'));registry.register(tool('tool_b'));const result=await new AgentRuntime(new FakeProvider(),registry).run({goal:'x',systemPolicy:'p',model:'fake',context:{runId:'r',role:'ADMIN'},budget:{maxIterations:5,maxToolCalls:1,maxTokens:100,timeoutMs:5000}});assert.equal(result.status,'INSUFFICIENT_DATA');assert.equal(result.reason,'TOOL_BUDGET_EXCEEDED');});
test('registry blocks non-admin access and write tools',async()=>{const registry=new ToolRegistry();registry.register(tool('tool_a'));await assert.rejects(()=>registry.execute('tool_a',{}, {runId:'r',role:'VIEWER'}));});

test('feeds rejected final contract back to the model for correction',async()=>{class RepairProvider implements LlmProvider{calls=0;seen:any[]=[];async complete(input:any){this.seen.push(structuredClone(input.messages));this.calls++;return {message:{role:'assistant' as const,content:this.calls===1?'{\"roomStrategies\":[{\"assessment\":\"ok\"}]}':'{\"roomStrategies\":[{\"assessment\":\"ok\",\"objective\":\"fixed\"}]}'}};}}const provider=new RepairProvider();const registry=new ToolRegistry();const result=await new AgentRuntime(provider,registry).run({goal:'x',systemPolicy:'p',model:'fake',context:{runId:'r',role:'ADMIN'},budget:{maxIterations:3,maxToolCalls:1,maxTokens:100,timeoutMs:5000},validateFinal:(content)=>{const parsed=JSON.parse(content);if(!parsed.roomStrategies[0].objective)throw new Error('Missing objective at strategy 0');}});assert.equal(result.status,'COMPLETED');assert.equal(result.iterations,2);assert.match(provider.seen[1].at(-1).content,/Missing objective/);assert.match(result.final!,/\"objective\":\"fixed\"/);});

test('preflight evidence disables redundant model tools', async () => { class FinalProvider implements LlmProvider{tools:any[]=[];choices:any[]=[];async complete(input:any){this.tools.push(input.tools);this.choices.push(input.toolChoice);return {message:{role:'assistant' as const,content:'final'}};}} const provider=new FinalProvider(); const registry=new ToolRegistry();registry.register(tool('tool_a')); const result=await new AgentRuntime(provider,registry).run({goal:'x',systemPolicy:'p',model:'fake',context:{runId:'r',role:'ADMIN'},budget:{maxIterations:1,maxToolCalls:3,maxTokens:100,timeoutMs:5000},preflightTool:{name:'tool_a',arguments:{}}}); assert.equal(result.status,'COMPLETED'); assert.deepEqual(provider.tools,[[]]); assert.deepEqual(provider.choices,['none']); });

test('allows two rejected finals to use a third bounded repair call', async () => { class MultiRepairProvider implements LlmProvider { calls=0; async complete(){ this.calls++; return { message: { role:'assistant' as const, content: this.calls < 3 ? '{"roomStrategies":[{}]}' : '{"roomStrategies":[{"assessment":"ok","objective":"fixed"}]}' } }; } } const provider=new MultiRepairProvider(); const result=await new AgentRuntime(provider,new ToolRegistry()).run({goal:'x',systemPolicy:'p',model:'fake',context:{runId:'r',role:'ADMIN'},budget:{maxIterations:3,maxToolCalls:1,maxTokens:100,timeoutMs:5000},validateFinal:(content)=>{const strategy=JSON.parse(content).roomStrategies[0];if(!strategy.objective)throw new Error('Missing objective');}}); assert.equal(result.status,'COMPLETED'); assert.equal(result.iterations,3); assert.equal(provider.calls,3); });
