import {test} from 'node:test';import * as assert from 'node:assert/strict';import {availableRoomMetricReferences,validateAgentStrategyOutput} from './strategy-validator';
const context={rooms:new Map([['r1',{active:true,periodKeys:new Set(['thisWeek']),availableFields:new Set(['occupancy','revenue']),periodDates:new Map([['thisWeek',{from:'2026-08-31',to:'2026-09-06'}]])}]]),allowedChannels:new Set(['airbnb','zalo','sale','khac']),maxDiscountPercent:40};
const valid=()=>({executiveSummary:'ok',roomStrategies:[{roomId:'r1',periodKey:'thisWeek',priority:'HIGH',assessment:'risk',objective:'increase qualified occupancy',evidence:['occupancy=20'],pricingRecommendation:{discountPercent:5},channelRecommendation:{channels:['airbnb']},dateRange:{from:'2026-08-31',to:'2026-09-06'},dataReferences:['occupancy'],targetOccupancy:40,targetRevenue:1000000,confidence:.8}],companyActions:[],missingData:[]});
test('accepts evidence-backed active room strategy',()=>assert.equal(validateAgentStrategyOutput(valid(),context).roomStrategies.length,1));
test('blocks hallucinated room and period',()=>{const x=valid();x.roomStrategies[0].roomId='fake';assert.throws(()=>validateAgentStrategyOutput(x,context));});
test('blocks unsupported evidence references and channels',()=>{const x=valid();x.roomStrategies[0].dataReferences=['competitorPrice'];assert.throws(()=>validateAgentStrategyOutput(x,context));const y=valid();y.roomStrategies[0].channelRecommendation.channels=['fake-ota'];assert.throws(()=>validateAgentStrategyOutput(y,context));});
test('blocks unapproved execution claims and discount above guardrail',()=>{const x:any=valid();x.roomStrategies[0].executed=true;assert.throws(()=>validateAgentStrategyOutput(x,context));const y=valid();y.roomStrategies[0].pricingRecommendation.discountPercent=50;assert.throws(()=>validateAgentStrategyOutput(y,context));});
test('derives canonical references from real nested output and excludes null/unavailable data',()=>{
 const fields=availableRoomMetricReferences({roomCode:'A08.10',building:{code:'OPERA'},roomType:{name:'4PN'},operationalStatus:'OCCUPIED',bookedNights:0,occupancy:0,bookedNightRevenue:0,adr:null,revPar:0,availability:{vacantNights:7,sellableNights:7,assumption:'calendar nights only'},economics:{monthlyCost:null,profit:null,revenueGap:null,breakEvenReached:null,requiredADRToBreakEven:null},referencePrice:9500000,discountablePrice:9000000,unavailable:{bookingPace:'UNAVAILABLE',gaps:'UNAVAILABLE'}});
 assert.equal(fields.has('calendarVacantNights'),true);assert.equal(fields.has('discountablePrice'),true);assert.equal(fields.has('adr'),false);assert.equal(fields.has('monthlyCost'),false);assert.equal(fields.has('bookingPace'),false);assert.equal(fields.has('gaps'),false);assert.equal(fields.has('profit'),false);
});

test('requires assessment and objective separately',()=>{const a:any=valid();delete a.roomStrategies[0].assessment;assert.throws(()=>validateAgentStrategyOutput(a,context),/Missing assessment/);const o:any=valid();delete o.roomStrategies[0].objective;assert.throws(()=>validateAgentStrategyOutput(o,context),/Missing objective/);});
