import 'reflect-metadata';
import * as assert from 'node:assert/strict';
import { randomBytes } from 'crypto';
import * as bcrypt from 'bcryptjs';
import { NestFactory } from '@nestjs/core';
import { Module, ValidationPipe } from '@nestjs/common';
import { JwtService } from '@nestjs/jwt';
import { ConfigModule } from '../config/config.module';
import { PrismaModule } from '../prisma/prisma.module';
import { AuthModule } from '../auth/auth.module';
import { ReservationsModule } from '../reservations/reservations.module';
import { PricingModule } from '../pricing/pricing.module';
import { ChatbotModule } from './chatbot.module';
import { EventEmitterModule } from '@nestjs/event-emitter';
import { PrismaService } from '../prisma/prisma.service';
import { ResponseInterceptor } from '../common/interceptors/response.interceptor';
import { ReservationsService } from '../reservations/reservations.service';
import { ReservationActionsService } from '../reservations/reservation-actions.service';

@Module({ imports: [ConfigModule, PrismaModule, AuthModule, EventEmitterModule.forRoot(), ReservationsModule, PricingModule, ChatbotModule] })
class TestApplicationModule {}

async function main() {
  const target = new URL(process.env.DATABASE_URL ?? '');
  if (target.hostname !== '127.0.0.1' || target.port !== '55432' || target.pathname !== '/chatbot_test') throw new Error('Tests require the isolated chatbot_test database on loopback:55432');
  process.env.JWT_SECRET = 'isolated-chatbot-test-secret-not-production';
  process.env.AI_CEO_WORKER_ENABLED = 'false';
  const app = await NestFactory.create(TestApplicationModule, { logger: ['error'] });
  app.setGlobalPrefix('api');
  app.useGlobalInterceptors(new ResponseInterceptor());
  app.useGlobalPipes(new ValidationPipe({ whitelist: true, transform: true, forbidNonWhitelisted: true }));
  await app.init();
  const prisma = app.get(PrismaService);
  let webhookCount = 0;
  (app.get(ReservationsService) as any).sendBookingWebhook = async () => { webhookCount += 1; };
  (app.get(ReservationActionsService) as any).sendBookingWebhook = async () => { webhookCount += 1; };
  await app.listen(0, '127.0.0.1');
  const base = `${await app.getUrl()}/api`;
  const prefix = `test-${randomBytes(5).toString('hex')}`;
  const syntheticPhone = `09${String(randomBytes(4).readUInt32BE() % 100000000).padStart(8, '0')}`;
  const user = await prisma.user.create({ data: { email: `${prefix}@example.invalid`, password: await bcrypt.hash('test-only-password', 4), fullName: 'Synthetic Admin', role: 'ADMIN' } });
  const jwt = new JwtService().sign({ sub: user.id }, { secret: process.env.JWT_SECRET, expiresIn: '1h' });
  const human = { Authorization: `Bearer ${jwt}` };
  const scopes = ['availability:read', 'pricing:read', 'customer:read', 'hold:read', 'hold:write', 'booking:read', 'booking:write'].map((value) => `chatbot:${value}`);
  const createKey = async (keyScopes: string[]) => {
    const raw = `hk_${randomBytes(24).toString('hex')}`;
    const record = await prisma.apiKey.create({ data: { name: prefix, keyPrefix: raw.slice(0, 8), keyHash: await bcrypt.hash(raw, 4), scopes: keyScopes } });
    return { record, headers: { 'X-API-Key': raw } };
  };
  const key = await createKey(scopes);
  const other = await createKey(scopes);
  const readOnly = await createKey(['chatbot:availability:read']);
  const legacy = await createKey([]);
  const request = async (method: string, path: string, body?: any, headers: Record<string, string> = key.headers) => {
    const response = await fetch(base + path, { method, headers: { 'Content-Type': 'application/json', ...headers }, ...(body === undefined ? {} : { body: JSON.stringify(body) }) });
    return { status: response.status, body: await response.json() as any };
  };
  const success = async (method: string, path: string, body?: any, headers?: Record<string, string>) => {
    const response = await request(method, path, body, headers);
    assert.ok(response.status >= 200 && response.status < 300, `${method} ${path}: ${JSON.stringify(response)}`);
    assert.equal(response.body.ok, true);
    return response.body.data;
  };
  const error = async (method: string, path: string, body: any, code: string, headers?: Record<string, string>) => {
    const response = await request(method, path, body, headers);
    assert.ok(response.status >= 400, `${path} unexpectedly succeeded`);
    assert.equal(response.body.error?.code, code, JSON.stringify(response));
  };
  const idempotent = (value: string) => ({ ...key.headers, 'Idempotency-Key': `${prefix}-${value}` });
  const building = await prisma.building.create({ data: { code: prefix, name: 'Synthetic Building' } });
  const roomType = await prisma.roomType.create({ data: { name: prefix, basePrice: 2000000, amenities: [] } });
  const room = async (name: string, price: number | null = 2000000) => prisma.room.create({ data: { number: `${prefix}-${name}`, roomTypeId: roomType.id, buildingId: building.id, price } });
  const mainRoom = await room('A07.06');
  const dates = { checkInDate: '2026-10-10', checkOutDate: '2026-10-15' };
  const input = { roomId: mainRoom.id, ...dates, discount: 'yes' };
  const rulePath = `/room-types/${roomType.id}/stay-discount-rules`;
  const hold = (payload: any, operation: string) => success('POST', '/chatbot/holds', payload, idempotent(operation));
  const legacyPayload = (roomId: string, overrides = {}) => ({ roomId, ...dates, primaryGuestName: 'Synthetic Legacy Guest', pricePerNight: 2000000, source: 'khac', ...overrides });
  try {
    const rule = await success('POST', rulePath, { minValue: 4, minUnit: 'DAY', maxValue: 5, maxUnit: 'DAY', discountPerNight: 200000 }, human);
    assert.equal(rule.minNights, 4);
    await error('POST', rulePath, { minValue: 5, minUnit: 'DAY', maxValue: 8, maxUnit: 'DAY', discountPerNight: 1 }, 'DISCOUNT_RULE_OVERLAP', human);
    const monthly = await success('POST', rulePath, { minValue: 6, minUnit: 'MONTH', maxValue: 1, maxUnit: 'YEAR', discountPerNight: 300000 }, human);
    assert.equal(monthly.minNights, 180); assert.equal(monthly.maxNights, 365);
    await success('DELETE', `${rulePath}/${monthly.id}`, undefined, human);
    const searches = await success('GET', `/reservations/quick-room-search?roomTypeId=${roomType.id}&checkInDate=${dates.checkInDate}&checkOutDate=${dates.checkOutDate}`);
    assert.ok(searches.some((item: any) => item.roomId === mainRoom.id));
    assert.ok(searches.every((item: any) => 'floor' in item && 'description' in item));
    assert.equal((await success('POST', '/pricing/price-check', { ...input, discount: 'no' })).pricing.total, 10000000);
    const quote = await success('POST', '/pricing/price-check', input);
    assert.equal(quote.pricing.total, 9000000);
    assert.equal(quote.stay.nights, 5);
    const held = await hold(input, 'golden-hold');
    assert.equal(held.status, 'ACTIVE'); assert.equal(held.pricing.total, 9000000);
    assert.deepEqual(await hold(input, 'golden-hold'), held);
    await error('POST', '/chatbot/holds', { ...input, discount: 'no' }, 'IDEMPOTENCY_CONFLICT', idempotent('golden-hold'));
    await error('POST', '/pricing/price-check', input, 'ROOM_TEMPORARILY_HELD');
    await error('POST', '/reservations', legacyPayload(mainRoom.id), 'ROOM_TEMPORARILY_HELD', human);
    const afterHold = await success('GET', `/reservations/quick-room-search?roomTypeId=${roomType.id}&checkInDate=${dates.checkInDate}&checkOutDate=${dates.checkOutDate}`);
    assert.ok(!afterHold.some((item: any) => item.roomId === mainRoom.id));
    await success('PATCH', `${rulePath}/${rule.id}`, { discountPerNight: 250000 }, human);
    const bookInput = { holdId: held.holdId, guest: { fullName: 'Synthetic Golden Guest', phone: syntheticPhone, email: `${prefix}@example.invalid` }, adults: 2 };
    const booked = await success('POST', '/chatbot/bookings/from-hold', bookInput, idempotent('golden-book'));
    assert.equal(booked.pricing.total, 9000000);
    assert.deepEqual(await success('POST', '/chatbot/bookings/from-hold', bookInput, idempotent('golden-book')), booked);
    const stored = await prisma.reservation.findUnique({ where: { id: booked.reservationId }, include: { guests: true } });
    assert.equal(await prisma.reservation.count({ where: { id: booked.reservationId } }), 1);
    assert.equal(Number(stored.pricePerNight), 2000000); assert.equal(Number(stored.discountAmount), 1000000); assert.equal(Number(stored.totalAmount), 9000000);
    assert.equal(stored.guests.length, 1);
    assert.equal((await success('GET', `/chatbot/holds/${held.holdId}`)).status, 'CONVERTED');
    await error('POST', '/chatbot/bookings/from-hold', bookInput, 'HOLD_ALREADY_CONVERTED', idempotent('different-book'));
    const knownGuestRoom = await room('known-guest');
    const knownHold = await hold({ ...input, roomId: knownGuestRoom.id, channelType: 'zalo_personal', externalThreadId: 'synthetic-thread' }, 'known-hold');
    const knownBooked = await success('POST', '/chatbot/bookings/from-hold', { holdId: knownHold.holdId, guestId: stored.guests[0].guestId }, idempotent('known-book'));
    const knownStored = await prisma.reservation.findUnique({ where: { id: knownBooked.reservationId }, include: { guests: true } });
    assert.equal(knownStored.guests[0].guestId, stored.guests[0].guestId); assert.equal(knownStored.threadId, 'synthetic-thread');
    const safe = await success('GET', `/chatbot/bookings/${booked.reservationId}`);
    assert.equal(safe.pricing.basePricePerNight, 2000000); assert.equal(safe.pricing.totalDiscount, 1000000); assert.equal(safe.pricing.total, 9000000);
    assert.ok(!('internalNotes' in safe)); assert.ok(!('idNumber' in safe.guest));
    await error('GET', `/chatbot/bookings/${booked.reservationId}`, undefined, 'RESERVATION_NOT_FOUND', other.headers);
    await error('GET', `/chatbot/holds/${held.holdId}`, undefined, 'HOLD_NOT_FOUND', other.headers);
    const context = await success('POST', '/chatbot/customer-context', { phone: `+84 ${syntheticPhone.slice(1)}` });
    assert.equal(context.matchStatus, 'MATCHED'); assert.equal(context.relationship, 'BOOKED');
    assert.equal(context.upcomingReservations[0].reservationId, booked.reservationId);
    assert.equal((await success('POST', '/chatbot/customer-context', { phone: '0909999999' })).matchStatus, 'NONE');
    const noRule = await success('POST', '/pricing/price-check', { roomId: knownGuestRoom.id, checkInDate: '2026-11-01', checkOutDate: '2026-11-03', discount: 'yes' });
    assert.equal(noRule.pricing.total, 4000000); assert.equal(noRule.pricing.discountApplied, false);
    await prisma.guest.create({ data: { fullName: 'Synthetic Duplicate', phone: `${syntheticPhone.slice(0, 4)} ${syntheticPhone.slice(4)}` } });
    assert.equal((await success('POST', '/chatbot/customer-context', { phone: syntheticPhone })).matchStatus, 'AMBIGUOUS');
    const fallback = await room('fallback', null);
    assert.equal((await success('POST', '/pricing/price-check', { ...input, roomId: fallback.id })).pricing.priceSource, 'ROOM_TYPE_BASE_PRICE');
    await prisma.room.update({ where: { id: fallback.id }, data: { status: 'MAINTENANCE' } });
    await error('POST', '/pricing/price-check', { ...input, roomId: fallback.id }, 'ROOM_MAINTENANCE');
    const maintenanceSearch = await success('GET', `/reservations/quick-room-search?roomTypeId=${roomType.id}`);
    assert.ok(!maintenanceSearch.some((item: any) => item.roomId === fallback.id));
    const race = await room('race');
    const raceResults = await Promise.all([request('POST', '/chatbot/holds', { ...input, roomId: race.id }, idempotent('race-a')), request('POST', '/chatbot/holds', { ...input, roomId: race.id }, idempotent('race-b'))]);
    assert.equal(raceResults.filter((result) => result.status < 300).length, 1);
    assert.equal(raceResults.find((result) => result.status >= 400).body.error.code, 'ROOM_TEMPORARILY_HELD');
    const racingHold = raceResults.find((result) => result.status < 300).body.data;
    await prisma.roomHold.update({ where: { id: racingHold.holdId }, data: { expiresAt: new Date(Date.now() - 1000) } });
    assert.equal((await success('GET', `/chatbot/holds/${racingHold.holdId}`)).status, 'EXPIRED');
    await error('POST', '/chatbot/bookings/from-hold', { holdId: racingHold.holdId, guestId: stored.guests[0].guestId }, 'HOLD_EXPIRED', idempotent('expired-book'));
    assert.equal((await success('POST', '/pricing/price-check', { ...input, roomId: race.id })).available, true);
    const released = await hold({ ...input, roomId: race.id }, 'release-hold');
    const releaseResult = await success('POST', `/chatbot/holds/${released.holdId}/release`, undefined, idempotent('release'));
    assert.equal(releaseResult.status, 'RELEASED');
    assert.deepEqual(await success('POST', `/chatbot/holds/${released.holdId}/release`, undefined, idempotent('release')), releaseResult);
    const raceLegacy = await room('race-legacy');
    const simultaneous = await Promise.all([request('POST', '/chatbot/holds', { ...input, roomId: raceLegacy.id }, idempotent('race-legacy')), request('POST', '/reservations', legacyPayload(raceLegacy.id), human)]);
    assert.equal(simultaneous.filter((result) => result.status < 300).length, 1);
    const updateRaceRoom = await room('race-update');
    const updateRaceBooking = await success('POST', '/reservations', legacyPayload(updateRaceRoom.id), human);
    const newDates = { checkInDate: '2026-10-20', checkOutDate: '2026-10-25' };
    const updateRace = await Promise.all([request('POST', '/chatbot/holds', { roomId: updateRaceRoom.id, ...newDates }, idempotent('race-update')), request('PATCH', `/reservations/${updateRaceBooking.id}`, newDates, human)]);
    assert.equal(updateRace.filter((result) => result.status < 300).length, 1);
    const legacyRoom = await room('legacy');
    const legacyBooking = await success('POST', '/reservations', legacyPayload(legacyRoom.id), human);
    await success('GET', `/reservations/${legacyBooking.id}`, undefined, human);
    await success('PATCH', `/reservations/${legacyBooking.id}`, { notes: 'Synthetic edit' }, human);
    const targetRoom = await room('target');
    const targetHold = await hold({ ...input, roomId: targetRoom.id }, 'target-held');
    await error('POST', `/reservations/${legacyBooking.id}/assign-room`, { roomId: targetRoom.id }, 'ROOM_TEMPORARILY_HELD', human);
    await error('POST', `/reservations/${legacyBooking.id}/change-room`, { newRoomId: targetRoom.id, reason: 'Synthetic test' }, 'ROOM_TEMPORARILY_HELD', human);
    await error('PATCH', `/reservations/${legacyBooking.id}`, { roomId: targetRoom.id }, 'ROOM_TEMPORARILY_HELD', human);
    await success('POST', `/chatbot/holds/${targetHold.holdId}/release`, undefined, idempotent('release-target'));
    await success('POST', `/reservations/${legacyBooking.id}/assign-room`, { roomId: targetRoom.id }, human);
    await success('POST', `/reservations/${legacyBooking.id}/change-room`, { newRoomId: legacyRoom.id, reason: 'Synthetic test' }, human);
    const extensionHold = await hold({ roomId: legacyRoom.id, checkInDate: '2026-10-15', checkOutDate: '2026-10-17' }, 'extension-hold');
    await error('POST', `/reservations/${legacyBooking.id}/extend`, { newCheckOutDate: '2026-10-17', reason: 'Synthetic test' }, 'ROOM_TEMPORARILY_HELD', human);
    await success('POST', `/chatbot/holds/${extensionHold.holdId}/release`, undefined, idempotent('release-extension'));
    await success('POST', `/reservations/${legacyBooking.id}/extend`, { newCheckOutDate: '2026-10-17', reason: 'Synthetic test' }, human);
    await success('POST', `/reservations/${legacyBooking.id}/check-in`, {}, human);
    await success('POST', `/reservations/${legacyBooking.id}/check-out`, {}, human);
    const cancelRoom = await room('cancel');
    const cancelBooking = await success('POST', '/reservations', legacyPayload(cancelRoom.id), human);
    await success('POST', `/reservations/${cancelBooking.id}/cancel`, { cancelReason: 'Synthetic cancellation' }, human);
    await success('GET', '/reservations', undefined, human);
    await success('GET', '/reservations', undefined, legacy.headers);
    await success('GET', `/reservations/quick-room-search?roomTypeId=${roomType.id}`, undefined, legacy.headers);
    for (const path of ['/reservations', `/reservations/${booked.reservationId}`]) await error('GET', path, undefined, 'INSUFFICIENT_SCOPE', readOnly.headers);
    await error('POST', '/reservations', legacyPayload(cancelRoom.id), 'INSUFFICIENT_SCOPE', readOnly.headers);
    await error('POST', '/pricing/price-check', input, 'INSUFFICIENT_SCOPE', readOnly.headers);
    await error('POST', '/chatbot/holds', input, 'IDEMPOTENCY_KEY_REQUIRED');
    const extra = await request('POST', '/chatbot/bookings/from-hold', { ...bookInput, totalAmount: 1 }, idempotent('arbitrary-price'));
    assert.equal(extra.status, 400);
    const invalid = await request('POST', '/pricing/price-check', input, { 'X-API-Key': 'invalid' });
    assert.equal(invalid.status, 401);
    await prisma.apiKey.update({ where: { id: other.record.id }, data: { isActive: false } });
    await error('POST', '/pricing/price-check', input, 'INVALID_API_KEY', other.headers);
    assert.ok(webhookCount >= 8, 'Legacy webhook call paths preserved and mocked; no external messages sent');
    console.log('PASS Golden Flow, price snapshot, replay, tenant isolation, identity, TTL, scopes, rule CRUD, real PostgreSQL races, and legacy reservation regression. No external webhook sent.');
  } finally {
    await app.close();
  }
}

main().catch((failure) => { console.error(failure); process.exitCode = 1; });
