import { BadRequestException, Injectable } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import { createCipheriv, createDecipheriv, createHash, randomBytes } from 'crypto';
import { PrismaService } from '../prisma/prisma.service';
import { OTA_CHANNELS, assertSafeCredentialShape, connectorNotReady, normalizeOtaChannel } from './ota-connector.policy';
@Injectable()
export class OtaConnectorsService {
  constructor(private readonly prisma: PrismaService, private readonly config: ConfigService) {}
  private key(){return createHash('sha256').update(this.config.get<string>('JWT_SECRET')||'chihome-ota-connectors').digest()}
  private encrypt(value:string){const iv=randomBytes(12),cipher=createCipheriv('aes-256-gcm',this.key(),iv),ciphertext=Buffer.concat([cipher.update(value,'utf8'),cipher.final()]);return [iv.toString('base64'),cipher.getAuthTag().toString('base64'),ciphertext.toString('base64')].join('.')}
  private decrypt(value:string){const [iv,tag,ciphertext]=value.split('.'),decipher=createDecipheriv('aes-256-gcm',this.key(),Buffer.from(iv,'base64'));decipher.setAuthTag(Buffer.from(tag,'base64'));return Buffer.concat([decipher.update(Buffer.from(ciphertext,'base64')),decipher.final()]).toString('utf8')}
  private public(row:any){return {id:row.id,channel:row.channel,displayName:row.displayName,enabled:row.enabled,configured:Boolean(row.credentialCiphertext),credentialFields:OTA_CHANNELS.AIRBNB.credentialFields,createdAt:row.createdAt,updatedAt:row.updatedAt}}
  async list(){return (await this.prisma.otaConnector.findMany({orderBy:{channel:'asc'}})).map(row=>this.public(row))}
  async configure(channelInput:string,credentials:unknown,enabled:boolean|undefined,actorId?:string){const channel=normalizeOtaChannel(channelInput),safe=assertSafeCredentialShape(credentials),metadata={fields:Object.keys(safe).sort(),updatedAt:new Date().toISOString(),adapter:'NONE'},row=await this.prisma.otaConnector.upsert({where:{channel},update:{credentialCiphertext:this.encrypt(JSON.stringify(safe)),credentialMetadata:metadata,enabled:Boolean(enabled),displayName:OTA_CHANNELS.AIRBNB.displayName},create:{channel,displayName:OTA_CHANNELS.AIRBNB.displayName,credentialCiphertext:this.encrypt(JSON.stringify(safe)),credentialMetadata:metadata,enabled:Boolean(enabled),createdBy:actorId||null}});await this.prisma.otaConnectorAudit.create({data:{connectorId:row.id,action:'CONFIGURED',actorId:actorId||null,request:{channel,credentialFields:metadata.fields,enabled:Boolean(enabled)},result:{adapter:'NONE',externalRequest:false}}});return this.public(row)}
  async preview(id:string,actorId?:string){const row=await this.prisma.otaConnector.findUnique({where:{id}});if(!row)throw new BadRequestException('Không tìm thấy OTA connector');if(row.credentialCiphertext){try{JSON.parse(this.decrypt(row.credentialCiphertext))}catch{throw new BadRequestException('Không thể đọc thông tin xác thực OTA đã lưu')}}const result={connector:this.public(row),adapter:'NONE',externalRequest:false,executable:false,reason:'Chưa có adapter OTA đã được phê duyệt; preview không gửi request ra ngoài.'};await this.prisma.otaConnectorAudit.create({data:{connectorId:row.id,action:'PREVIEWED',actorId:actorId||null,request:{externalRequest:false},result}});return result}
  async execute(id:string,actorId?:string){const row=await this.prisma.otaConnector.findUnique({where:{id}});if(!row)throw new BadRequestException('Không tìm thấy OTA connector');await this.prisma.otaConnectorAudit.create({data:{connectorId:row.id,action:'EXECUTION_BLOCKED',actorId:actorId||null,request:{externalRequest:false},result:{adapter:'NONE',externalRequest:false,blocked:true}}});throw connectorNotReady()}
  async audits(id:string){return this.prisma.otaConnectorAudit.findMany({where:{connectorId:id},select:{id:true,action:true,actorId:true,request:true,result:true,createdAt:true},orderBy:{createdAt:'desc'},take:100})}
}
